### ISSUE TITLE
If statements and general codebase formatting

### ISSUE THREAD

**Issue by joaquimgamero** [GonzoVM/bin2dec#2]
In general the codebase lacks proper formatting for `if` statements:

https://github.com/GonzoVM/bin2dec/blob/da337eb41288e0aa38f88bbb2373b386795908be/src/excep_handl.js#L18

https://github.com/GonzoVM/bin2dec/blob/da337eb41288e0aa38f88bbb2373b386795908be/src/excep_handl.js#L31

https://github.com/GonzoVM/bin2dec/blob/da337eb41288e0aa38f88bbb2373b386795908be/src/excep_handl.js#L46

Code format guidelines are important for:

- Readability: Ensures code is easily understood by anyone.
- Maintainability: Consistent formatting helps in spotting bugs and improvements.
- Collaboration: Helps multiple developers work on the same codebase without style clashes.
- Onboarding: Eases the process for newcomers to understand the code.
- Automation: Supports tools like linters to maintain code quality.
- Reduced Errors: Consistency minimizes mistakes.
- Professionalism: Shows discipline and care in coding practices.
- Efficiency: Consistent style speeds up coding tasks.
- Better Design: Some standards indirectly promote good coding design.
- Documentation: Consistent comments and naming act as in-code documentation.

The goal of this issue is to make the codebase format switch to a healthier state. Given the scope of this repo is small, we have 2 options:

- Manual formatting. In case we're not sure on what formatting to follow, please refer to [Google's JS style guidelines](http://google.github.io/styleguide/jsguide.html).
- Using a formatter like [prettier](https://prettier.io)

**Comment by GonzoVM** [comment]
thanks for this recommendations, I formatted all the code with prettier as you suggested.

I'll link the commit when I upload it.

**Comment by GonzoVM** [comment]
here is the commit: https://github.com/GonzoVM/bin2dec/commit/de058f42ab51c954cf95330ddd3cf7e615da85a7

**Comment by GonzoVM** [comment]
here is the commit: https://github.com/GonzoVM/bin2dec/commit/de058f42ab51c954cf95330ddd3cf7e615da85a7

**Comment by joaquimgamero** [comment]
Thanks Coche, nice effort! However, I prefer to keep this open until it's been merged to `main`, if that's okay. If its still in a secondary branch it's not yet "done".

**Comment by GonzoVM** [comment]
got it

**Comment by GonzoVM** [comment]
this was solved and the branch was merged with the main, so I close this issue.
