### ISSUE TITLE
Change handleConversion() to receive two parameters (source and target)

### ISSUE THREAD

**Issue by GonzoVM** [GonzoVM/bin2dec#5]
As of now the function handleConversion() is receiving the type of conversion as a parameter:
```html
        <input id="decToBin" type="button" value="binary" onclick="handleConversion('decToBin')" />
        <input id="decToHex" type="button" value="hexadecimal" onclick="handleConversion('decToHex')" />
        <input id="decToOct" type="button" value="octal" onclick="handleConversion('decToOct')" />
```

and is a clearer way to manage that function separating the input and the output number type, changing:
`handleConversion('decToBin')`
to:
`handleConversion('dec', 'bin')`

**Comment by GonzoVM** [comment]
Maybe is better to use the complete names ("decimal", "binary"... ) instead of "dec", "bin"... as I have been using on all the code but the function calling, but not sure about this point because I think is fairly clear to understand what it means "dec", "bin", "hex", and "oct".

**Comment by joaquimgamero** [comment]
> Maybe is better to use the complete names ("decimal", "binary"... ) instead of "dec", "bin"... as I have been using on all the code but the function calling, but not sure about this point because I think is fairly clear to understand what it means "dec", "bin", "hex", and "oct".

I tend to favour full words but in this case I think it's okay to use shorter values, so it's your call

**Comment by GonzoVM** [comment]
> > Maybe is better to use the complete names ("decimal", "binary"... ) instead of "dec", "bin"... as I have been using on all the code but the function calling, but not sure about this point because I think is fairly clear to understand what it means "dec", "bin", "hex", and "oct".
> 
> I tend to favour full words but in this case I think it's okay to use shorter values, so it's your call

Finally I preferred to use the complete name so I directly can manage the validation directly from this input so there's no need on create a new variable to this.
